"""Add custom_fields to User and Student

Revision ID: 024ee113227b
Revises: 54aa6e4c3582
Create Date: 2026-09-30 23:43:07.846604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024ee113227b'
down_revision: Union[str, Sequence[str], None] = '54aa6e4c3582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('custom_fields', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('custom_fields_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_fields_config')
    op.drop_column('students', 'custom_fields')
    # ### end Alembic commands ###
