"""Add SMTP fields to User

Revision ID: 54aa6e4c3582
Revises: ab90d4cebb85
Create Date: 2026-09-23 18:46:50.908429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54aa6e4c3582'
down_revision: Union[str, Sequence[str], None] = 'ab90d4cebb85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('smtp_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('smtp_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'smtp_password')
    op.drop_column('users', 'smtp_username')
    op.drop_column('users', 'smtp_port')
    op.drop_column('users', 'smtp_host')
    # ### end Alembic commands ###
